# Generated by Django 3.2.9 on 2021-12-01 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0003_auto_20211201_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='women',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
